[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
env_logger = "0.11.5"
simplex-chat = { path = "../simplex-chat" }
tokio = { version = "1.41.1", features = ["full"] }
